[package]
name = "clarity"
version = "0.5.1"
authors = ["Michał Papierski <michal@papierski.net>, Justin Kilpatrick <justin@althea.net>"]
autotests = true
include = [
    "**/*.rs",
    "Cargo.toml"
]
description = "Lightweight Ethereum client"
repository = "https://github.com/althea-net/clarity"
license-file = "LICENSE"
edition = "2021"

[badges]
travis-ci = { repository = "althea-net/clarity", branch = "master" }

[dependencies]
serde = "1.0"
serde-rlp = { git = "https://github.com/monacohq/serde-rlp.git", rev = "796be5c" }
num-bigint = { version = "0.4", default-features = false, features = ["serde"] }
num-traits = "0.2"
serde_bytes = "0.11"
sha3 = "0.10"
secp256k1 = { version = "0.21", features = ["recovery"] }
lazy_static = "1.4"
serde_derive = "1.0"
num256 = "0.3"

[[test]]
name = "transaction_tests"
harness = false

[dev-dependencies]
futures = "0.1"
rand = "0.8"
rustc-test = "0.3.0"
serde_json = "1.0"
web3 = "0.6"
criterion = "0.3"
openssl = {version = "0.10", features = ["vendored"]}

[[bench]]
name = "crypto_bench"
harness = false

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
incremental = false
